### ISSUE TITLE
Remove unsupported configuration settings

### ISSUE THREAD

**Issue by peel** [snowplow-incubator/snowplow-micro#118]
Example config file (taken literally from stream-collector) contains settings that are not supported by micro.
One such example is SSL configuration. Neither `collector.ssl` nor `akka.ssl-config` are respected in micro. These fields should be removed as they are confusing.

**Comment by istreeter** [comment]
Hey @peel which example config file are you talking about here?

The latest release of micro has [this example config file](https://github.com/snowplow-incubator/snowplow-micro/blob/micro-1.3.4/example/micro.conf) which to me looks perfect.  There is only one configurable option.

Has this issue been fixed already?  Or were you looking at a different example file?

**Comment by peel** [comment]
Seems to have been fixed now.
