### ISSUE TITLE
Default Iglu Client Resolver has no cache

### ISSUE THREAD

**Issue by paulboocock** [snowplow-incubator/snowplow-micro#122]
When running Micro with no configuration (`docker run -p 9090:9090 snowplow/snowplow-micro:1.3.4`) the responses are significantly slower than when run with the `--iglu` flag and the example `iglu.json`.

This is due to `iglu.json` having a default cacheSize of 500, but the built in default Iglu Resolve has `None`: https://github.com/snowplow-incubator/snowplow-micro/blob/master/src/main/scala/com.snowplowanalytics.snowplow.micro/ConfigHelper.scala#L48

We can pass a `ResolverCache` here instead of `None`, probably with a cache of 500 like the default `iglu.json`, which should improve performance when running Micro with zero config.

**Comment by istreeter** [comment]
closed by #123 

Enrich 3.6.1 made quite big changes to how it uses Iglu Client.  In upgrading Micro to use 3.6.1 it became natural to add a cache at the same time.
