### ISSUE TITLE
Snowplow Micro does not create a listen on HTTPS port

### ISSUE THREAD

**Issue by TC117** [snowplow-incubator/snowplow-micro#78]
**Describe the bug**
Snowplow Micro does not create an listen on HTTPS port setting in micro.conf

```
  # The collector runs as a web service specified on the following interface and port.
  interface = "0.0.0.0"
  port = "9090"

   # optional SSL/TLS configuration
  ssl {
    enable = true
    # whether to redirect HTTP to HTTPS
    redirect = false
    port = 9543
  }
```
It still listens on port 9090 but I think with SSL enabled its should listen on both 9090 and 9543

```
[root@localhost ~]# netstat -tulpn | grep LISTEN
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      7074/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      1057/master
tcp        0      0 127.0.0.1:6010          0.0.0.0:*               LISTEN      1406/sshd: root@pts
tcp        0      0 127.0.0.1:6011          0.0.0.0:*               LISTEN      1811/sshd: root@pts
tcp6       0      0 :::22                   :::*                    LISTEN      7074/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      1057/master
tcp6       0      0 ::1:6010                :::*                    LISTEN      1406/sshd: root@pts
tcp6       0      0 ::1:6011                :::*                    LISTEN      1811/sshd: root@pts
tcp6       0      0 :::9090                 :::*                    LISTEN      18769/java
[root@localhost ~]#
```

**To Reproduce**
enable SSL option

**Expected behavior**
should listen on both 9090 and 9543

**Screenshots**

**Environment (please complete the following information):**
 - OS: Centos
 - Version 7

**Additional context**

**Comment by angelsk** [comment]
The same thing happens in Docker. Even if I enable SSL and also bind the port in the Docker compose, it only listens on port 9090

**Comment by paulboocock** [comment]
This is definitely an improvement we can look into, although we'd probably want a nice solution for the certificates too. 

Running `ngrok` to create a `https` tunnel is a nice way to get Micro running under `https` - https://ngrok.com/

**Comment by angelsk** [comment]
> This is definitely an improvement we can look into, although we'd probably want a nice solution for the certificates too.
> 
> Running `ngrok` to create a `https` tunnel is a nice way to get Micro running under `https` - https://ngrok.com/

Ah - but I want to be able to run it in CI/CD. And I honestly have no idea how to do that with ngrok.
